const express = require('express');
const { handleExpenseWithSplitCreation, handleUserBalance, handleGetUsersExpensesWithSplits, } = require('../controllers/expenseControllers');
const {auth}= require('../middlewares/authMiddleware.js');
const  validate  = require('../middlewares/validateMiddleware.js');
const errorMiddleware = require('../middlewares/errorMiddleware.js');
const { UserBalanceSchema, groupExpenseWithSplitSchema, expenseSplitSchema } = require('../schemas/expenseSchemas.js');
const router = express.Router();
router.post("/createExpense",auth,validate(expenseSplitSchema),handleExpenseWithSplitCreation);
router.post("/netBalance",auth,validate(UserBalanceSchema),handleUserBalance);
router.get("/groupExpensesWithSplits/:groupId",auth,validate(groupExpenseWithSplitSchema),handleGetUsersExpensesWithSplits);
router.use(errorMiddleware);
module.exports = router;